apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-deployment
  namespace: dev
  labels:
    app: development-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: development-deployment
  template:
    metadata:
      labels:
        app: development-deployment
    spec:
      containers:
      - name: development-deployment
        image: europe-west1-docker.pkg.dev/qwiklabs-gcp-02-e64e7551736f/my-repository/sample-app-dev:v2.0
        ports:
        - containerPort: 8080
