apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-deployment
  labels:
    app: production-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: production-deployment
  template:
    metadata:
      labels:
        app: production-deployment
    spec:
      containers:
      - name: production-deployment
        image: europe-west1-docker.pkg.dev/qwiklabs-gcp-04-4d4689b9163b/my-repository/sample-app-prod:v1.0
        ports:
        - containerPort: 8080
